# Generated by Django 4.2.30 on 2026-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
