# Generated by Django 4.2.30 on 2026-08-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationotp_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='back_doc_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
