# Generated by Django 4.2.30 on 2026-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='electricity_bill_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='house_doc_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='doc_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('passport', 'Passport'), ('license', 'License')], default='citizenship', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
