# Generated by Django 4.2.30 on 2026-08-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
