# Generated by Django 4.2.30 on 2026-07-09 09:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0002_agreement_security_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveOutInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('structural_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('utility_status', models.CharField(choices=[('cleared', 'Cleared'), ('pending_bills', 'Pending Bills')], default='cleared', max_length=20)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_reason', models.TextField(blank=True)),
                ('refund_amount_calculated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_finalized', models.BooleanField(default=False)),
                ('report_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='move_out_inspection', to='agreements.agreement')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
    ]
