# Generated by Django 4.2.30 on 2026-08-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_utilitybill_electricity_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybill',
            name='electricity_amount',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='electricity_curr',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='electricity_prev',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='electricity_rate',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='garbage_amount',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='internet_amount',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='other_amount',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='water_amount',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='water_curr',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='water_prev',
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='water_rate',
        ),
    ]
