import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';
import { 
  DollarSign, 
  FileText, 
  PlusCircle, 
  CheckCircle, 
  Clock, 
  AlertTriangle,
  Zap,
  Droplet,
  Globe,
  Trash,
  Camera
} from 'lucide-react';

export default function Utilities() {
  const { user } = useAuth();
  const isLandlord = user?.role === 'landlord';

  const [bills, setBills] = useState([]);
  const [agreements, setAgreements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [submitLoading, setSubmitLoading] = useState(false);
  const [error, setError] = useState(null);

  // Bill & Utility Breakdown Form State
  const [form, setForm] = useState({
    agreement: '',
    billingMonth: '',
    dueDate: '',
    status: 'unpaid'
  });

  // Electricity (Meter: Previous & Current & Rate)
  const [electricity, setElectricity] = useState({
    previous: '',
    current: '',
    rate: 12
  });

  // Water (Meter: Previous & Current & Rate)
  const [water, setWater] = useState({
    previous: '',
    current: '',
    rate: 50
  });

  // Internet & Garbage (Direct Value Inputs)
  const [internetCharge, setInternetCharge] = useState('');
  const [garbageCharge, setGarbageCharge] = useState('');

  // Selected agreement prepopulated rent calculation
  const selectedAgreement = agreements.find(a => a.id === form.agreement) || agreements[0];
  const baseRentAmount = selectedAgreement ? parseFloat(selectedAgreement.rent_amount || 0) : 0;

  // Auto-calculated Utility Charges
  const elecUnits = Math.max(0, (parseFloat(electricity.current) || 0) - (parseFloat(electricity.previous) || 0));
  const elecCharge = elecUnits * (parseFloat(electricity.rate) || 12);

  const waterUnits = Math.max(0, (parseFloat(water.current) || 0) - (parseFloat(water.previous) || 0));
  const waterCharge = waterUnits * (parseFloat(water.rate) || 50);

  const directInternet = parseFloat(internetCharge) || 0;
  const directGarbage = parseFloat(garbageCharge) || 0;

  const totalUtilityCharge = elecCharge + waterCharge + directInternet + directGarbage;
  const calculatedTotalAmount = baseRentAmount + totalUtilityCharge;

  // Meter Photo Proof State (Multiple Photos Array)
  const [meterPhotos, setMeterPhotos] = useState([]);
  const [previewPhotoModal, setPreviewPhotoModal] = useState(null);

  const handlePhotoSelect = (e) => {
    const files = Array.from(e.target.files);
    files.forEach(file => {
      const reader = new FileReader();
      reader.onloadend = () => {
        setMeterPhotos(prev => [...prev, { id: Date.now() + Math.random(), url: reader.result, name: file.name }]);
      };
      reader.readAsDataURL(file);
    });
  };

  const removePhoto = (id) => {
    setMeterPhotos(prev => prev.filter(p => p.id !== id));
  };

  // Fetch initial data
  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      // Fetch bills
      const billsRes = await api.get('/utilities/bills/');
      setBills(billsRes.data.results || billsRes.data || []);

      if (isLandlord) {
        // Landlords need to see active agreements to select which lease to issue a bill for
        const agreementsRes = await api.get('/agreements/');
        const active = (agreementsRes.data.results || agreementsRes.data || []).filter(
          a => a.status === 'active'
        );
        setAgreements(active);
        if (active.length > 0) {
          setForm(f => ({ ...f, agreement: active[0].id }));
        }
      }
    } catch (err) {
      console.error(err);
      setError('Failed to load utilities data. Please try again.');
    } finally {
      setLoading(false);
    }
  }, [isLandlord]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Submit new utility bill
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (submitLoading) return;
    setError(null);

    if (!form.agreement || !form.billingMonth || !form.dueDate) {
      setError('Please fill in all required fields.');
      return;
    }

    setSubmitLoading(true);
    try {
      // 1. Create the Utility Bill with grand total amount (Base Rent + Utilities generated by landlord)
      const billPayload = {
        agreement: form.agreement,
        billing_month: form.billingMonth, // expecting "YYYY-MM-DD"
        total_amount: calculatedTotalAmount,
        due_date: form.dueDate,
        status: form.status
      };

      const billRes = await api.post('/utilities/bills/', billPayload);
      const createdBill = billRes.data;

      const readingDateStr = form.billingMonth || new Date().toISOString().substring(0, 10);

      // 2. Post Meter Reading for Electricity if entered
      if (electricity.current !== '') {
        await api.post('/utilities/readings/', {
          agreement: form.agreement,
          bill: createdBill.id,
          utility_type: 'electricity',
          previous_reading: parseFloat(electricity.previous) || 0,
          current_reading: parseFloat(electricity.current) || 0,
          reading_date: readingDateStr
        });
      }

      // 3. Post Meter Reading for Water if entered
      if (water.current !== '') {
        await api.post('/utilities/readings/', {
          agreement: form.agreement,
          bill: createdBill.id,
          utility_type: 'water',
          previous_reading: parseFloat(water.previous) || 0,
          current_reading: parseFloat(water.current) || 0,
          reading_date: readingDateStr
        });
      }

      // 4. Post Reading for Internet if entered
      if (directInternet > 0) {
        await api.post('/utilities/readings/', {
          agreement: form.agreement,
          bill: createdBill.id,
          utility_type: 'internet',
          previous_reading: 0,
          current_reading: directInternet,
          reading_date: readingDateStr
        });
      }

      // 5. Post Reading for Garbage if entered
      if (directGarbage > 0) {
        await api.post('/utilities/readings/', {
          agreement: form.agreement,
          bill: createdBill.id,
          utility_type: 'garbage',
          previous_reading: 0,
          current_reading: directGarbage,
          reading_date: readingDateStr
        });
      }

      // Reset form
      setForm({
        agreement: agreements[0]?.id || '',
        billingMonth: '',
        dueDate: '',
        status: 'unpaid'
      });
      setElectricity({ previous: '', current: '', rate: 12 });
      setWater({ previous: '', current: '', rate: 50 });
      setInternetCharge('');
      setGarbageCharge('');
      setMeterPhotos([]);

      // Refresh list
      await fetchData();
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.detail || 'Failed to issue utility bill.');
    } finally {
      setSubmitLoading(false);
    }
  };

  // Mark bill as Paid / Unpaid
  const handleToggleStatus = async (billId, currentStatus) => {
    const nextStatus = currentStatus === 'paid' ? 'unpaid' : 'paid';
    try {
      await api.patch(`/utilities/bills/${billId}/`, { status: nextStatus });
      // Refresh list
      const billsRes = await api.get('/utilities/bills/');
      setBills(billsRes.data.results || billsRes.data || []);
    } catch (err) {
      console.error(err);
      setError('Failed to update bill status.');
    }
  };

  // Download PDF Invoice
  const handleDownloadBillPDF = async (billId) => {
    try {
      const response = await api.get(`/utilities/bills/${billId}/pdf/`, {
        responseType: 'blob'
      });
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `utility_bill_${billId.slice(0, 8)}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      alert('Failed to download utility bill PDF. Please try again.');
    }
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'paid':
        return <span style={{ color: '#10b981', background: 'rgba(16, 185, 129, 0.1)', padding: '0.25rem 0.5rem', borderRadius: '2rem', fontSize: '0.8rem', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '0.25rem' }}><CheckCircle size={12}/> Paid</span>;
      case 'overdue':
        return <span style={{ color: '#ef4444', background: 'rgba(239, 68, 68, 0.1)', padding: '0.25rem 0.5rem', borderRadius: '2rem', fontSize: '0.8rem', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '0.25rem' }}><AlertTriangle size={12}/> Overdue</span>;
      default:
        return <span style={{ color: '#f59e0b', background: 'rgba(245, 158, 11, 0.1)', padding: '0.25rem 0.5rem', borderRadius: '2rem', fontSize: '0.8rem', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '0.25rem' }}><Clock size={12}/> Unpaid</span>;
    }
  };

  const getUtilityIcon = (type) => {
    switch (type) {
      case 'water':
        return <Droplet size={14} color="#3b82f6" />;
      case 'electricity':
        return <Zap size={14} color="#f59e0b" />;
      case 'internet':
        return <Globe size={14} color="#8b5cf6" />;
      default:
        return <FileText size={14} color="#10b981" />;
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '300px', color: 'var(--text-muted)' }}>
        Loading Utility Invoices...
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', fontFamily: 'var(--font-family)' }}>
      
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
        <DollarSign size={32} color="var(--primary-indigo)" />
        <div>
          <h1 style={{ fontSize: '1.75rem', fontWeight: 700, margin: 0 }}>Utility Bills</h1>
          <p style={{ color: 'var(--text-muted)', margin: 0 }}>
            {isLandlord ? 'Issue and monitor utility invoices for your tenants' : 'View and settle your utility invoices'}
          </p>
        </div>
      </div>

      {error && (
        <div style={{ padding: '1rem', background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', borderRadius: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <AlertTriangle size={18} />
          <span>{error}</span>
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: isLandlord ? '1fr 1.5fr' : '1fr', gap: '2rem', alignItems: 'start' }}>
        
        {/* Left Column: Issue Utility Bill Form (Landlord Only) */}
        {isLandlord && (
          <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <h2 style={{ fontSize: '1.25rem', fontWeight: 600, margin: 0, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <PlusCircle size={20} color="var(--primary-indigo)" /> Issue New Utility Bill
            </h2>

            {agreements.length === 0 ? (
              <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem', padding: '1rem', background: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.05)' }}>
                No active lease agreements found. You can only issue utility bills to tenants under active lease agreements.
              </div>
            ) : (
              <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                <div className="form-group" style={{ margin: 0 }}>
                  <label className="form-label">Lease Agreement (Tenant) *</label>
                  <select 
                    className="form-input"
                    value={form.agreement}
                    onChange={(e) => setForm({ ...form, agreement: e.target.value })}
                    required
                  >
                    {agreements.map((a) => (
                      <option key={a.id} value={a.id}>
                        {a.tenant?.full_name || a.tenant_email} ({a.property?.title})
                      </option>
                    ))}
                  </select>
                </div>

                <div className="form-group" style={{ margin: 0 }}>
                  <label className="form-label">Billing Month *</label>
                  <input 
                    type="date" 
                    className="form-input" 
                    value={form.billingMonth}
                    onChange={(e) => setForm({ ...form, billingMonth: e.target.value })}
                    required
                  />
                  <small style={{ color: 'var(--text-muted)', display: 'block', marginTop: '0.25rem' }}>Select any date within the billing month</small>
                </div>

                {/* Prepopulated Locked Rent Amount Card */}
                <div style={{
                  background: 'var(--bg-input)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '0.75rem',
                  padding: '0.95rem 1.1rem',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center'
                }}>
                  <div>
                    <label style={{ fontSize: '0.8rem', color: 'var(--accent-amber)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.04em', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
                      Base Monthly Rent 🔒
                    </label>
                    <span style={{ fontSize: '0.725rem', color: 'var(--text-muted)', display: 'block', marginTop: '0.15rem' }}>
                      Prepopulated from active lease
                    </span>
                  </div>
                  <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--accent-amber)' }}>
                    Rs. {baseRentAmount.toLocaleString()}
                  </div>
                </div>

                {/* 1. Electricity Meter Reading Section (Strict 3-Column Grid) */}
                <div style={{ 
                  background: 'var(--bg-card)', 
                  padding: '1rem', 
                  borderRadius: '0.85rem', 
                  border: '1px solid var(--border-color)', 
                  display: 'flex', 
                  flexDirection: 'column', 
                  gap: '0.75rem',
                  boxShadow: '0 4px 12px rgba(0,0,0,0.1)'
                }}>
                  <div style={{ fontWeight: 800, fontSize: '0.875rem', color: '#f59e0b', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                      <Zap size={16} /> 1. Electricity Meter Reading
                    </span>
                    <span style={{ fontSize: '0.825rem', fontWeight: 800, background: 'rgba(245, 158, 11, 0.12)', padding: '0.2rem 0.5rem', borderRadius: '0.4rem' }}>
                      = Rs. {elecCharge.toLocaleString()} ({elecUnits} units)
                    </span>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.5rem', width: '100%', boxSizing: 'border-box' }}>
                    <div style={{ minWidth: 0 }}>
                      <label style={{ fontSize: '0.725rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '0.25rem', whiteSpace: 'nowrap' }}>Prev (kWh)</label>
                      <input 
                        type="number" 
                        step="0.1" 
                        className="form-input" 
                        placeholder="0" 
                        value={electricity.previous} 
                        onChange={(e) => setElectricity({ ...electricity, previous: e.target.value })} 
                        style={{ width: '100%', boxSizing: 'border-box', padding: '0.45rem 0.5rem', fontSize: '0.85rem' }} 
                      />
                    </div>
                    <div style={{ minWidth: 0 }}>
                      <label style={{ fontSize: '0.725rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '0.25rem', whiteSpace: 'nowrap' }}>Curr (kWh)</label>
                      <input 
                        type="number" 
                        step="0.1" 
                        className="form-input" 
                        placeholder="0" 
                        value={electricity.current} 
                        onChange={(e) => setElectricity({ ...electricity, current: e.target.value })} 
                        style={{ width: '100%', boxSizing: 'border-box', padding: '0.45rem 0.5rem', fontSize: '0.85rem' }} 
                      />
                    </div>
                    <div style={{ minWidth: 0 }}>
                      <label style={{ fontSize: '0.725rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '0.25rem', whiteSpace: 'nowrap' }}>Rate (Rs/unit)</label>
                      <input 
                        type="number" 
                        step="0.5" 
                        className="form-input" 
                        value={electricity.rate} 
                        onChange={(e) => setElectricity({ ...electricity, rate: e.target.value })} 
                        style={{ width: '100%', boxSizing: 'border-box', padding: '0.45rem 0.5rem', fontSize: '0.85rem' }} 
                      />
                    </div>
                  </div>
                </div>

                {/* 2. Water Meter Reading Section (Strict 3-Column Grid) */}
                <div style={{ 
                  background: 'var(--bg-card)', 
                  padding: '1rem', 
                  borderRadius: '0.85rem', 
                  border: '1px solid var(--border-color)', 
                  display: 'flex', 
                  flexDirection: 'column', 
                  gap: '0.75rem',
                  boxShadow: '0 4px 12px rgba(0,0,0,0.1)'
                }}>
                  <div style={{ fontWeight: 800, fontSize: '0.875rem', color: '#3b82f6', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                      <Droplet size={16} /> 2. Water Meter Reading
                    </span>
                    <span style={{ fontSize: '0.825rem', fontWeight: 800, background: 'rgba(59, 130, 246, 0.12)', padding: '0.2rem 0.5rem', borderRadius: '0.4rem' }}>
                      = Rs. {waterCharge.toLocaleString()} ({waterUnits} units)
                    </span>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.5rem', width: '100%', boxSizing: 'border-box' }}>
                    <div style={{ minWidth: 0 }}>
                      <label style={{ fontSize: '0.725rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '0.25rem', whiteSpace: 'nowrap' }}>Prev (L/Units)</label>
                      <input 
                        type="number" 
                        step="0.1" 
                        className="form-input" 
                        placeholder="0" 
                        value={water.previous} 
                        onChange={(e) => setWater({ ...water, previous: e.target.value })} 
                        style={{ width: '100%', boxSizing: 'border-box', padding: '0.45rem 0.5rem', fontSize: '0.85rem' }} 
                      />
                    </div>
                    <div style={{ minWidth: 0 }}>
                      <label style={{ fontSize: '0.725rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '0.25rem', whiteSpace: 'nowrap' }}>Curr (L/Units)</label>
                      <input 
                        type="number" 
                        step="0.1" 
                        className="form-input" 
                        placeholder="0" 
                        value={water.current} 
                        onChange={(e) => setWater({ ...water, current: e.target.value })} 
                        style={{ width: '100%', boxSizing: 'border-box', padding: '0.45rem 0.5rem', fontSize: '0.85rem' }} 
                      />
                    </div>
                    <div style={{ minWidth: 0 }}>
                      <label style={{ fontSize: '0.725rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '0.25rem', whiteSpace: 'nowrap' }}>Rate (Rs/unit)</label>
                      <input 
                        type="number" 
                        step="1" 
                        className="form-input" 
                        value={water.rate} 
                        onChange={(e) => setWater({ ...water, rate: e.target.value })} 
                        style={{ width: '100%', boxSizing: 'border-box', padding: '0.45rem 0.5rem', fontSize: '0.85rem' }} 
                      />
                    </div>
                  </div>
                </div>

                {/* 3. Internet & Garbage Direct Value Inputs */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                  <div className="form-group" style={{ margin: 0, minWidth: 0 }}>
                    <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', color: '#8b5cf6', fontSize: '0.8rem', fontWeight: 700 }}>
                      <Globe size={14} /> Internet Bill (Rs.)
                    </label>
                    <input 
                      type="number" 
                      step="1"
                      className="form-input" 
                      placeholder="e.g. 1000"
                      value={internetCharge}
                      onChange={(e) => setInternetCharge(e.target.value)}
                      style={{ width: '100%', boxSizing: 'border-box' }}
                    />
                  </div>

                  <div className="form-group" style={{ margin: 0, minWidth: 0 }}>
                    <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', color: '#10b981', fontSize: '0.8rem', fontWeight: 700 }}>
                      <Trash size={14} /> Garbage Charge (Rs.)
                    </label>
                    <input 
                      type="number" 
                      step="1"
                      className="form-input" 
                      placeholder="e.g. 300"
                      value={garbageCharge}
                      onChange={(e) => setGarbageCharge(e.target.value)}
                      style={{ width: '100%', boxSizing: 'border-box' }}
                    />
                  </div>
                </div>

                <div className="form-group" style={{ margin: 0 }}>
                  <label className="form-label" style={{ fontWeight: 700 }}>Payment Due Date *</label>
                  <input 
                    type="date" 
                    className="form-input" 
                    value={form.dueDate}
                    onChange={(e) => setForm({ ...form, dueDate: e.target.value })}
                    required
                    style={{ width: '100%', boxSizing: 'border-box' }}
                  />
                </div>

                {/* Live Calculated Total Payable Banner with Full Itemization */}
                <div style={{
                  background: 'var(--pill-bg)',
                  border: '1px solid var(--pill-border)',
                  padding: '1.1rem',
                  borderRadius: '0.85rem',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '0.5rem',
                  boxShadow: '0 4px 16px rgba(0,0,0,0.15)'
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.45rem' }}>
                    <span style={{ fontSize: '0.825rem', color: 'var(--text-muted)', fontWeight: 600 }}>Base Rent</span>
                    <span style={{ fontSize: '0.875rem', fontWeight: 800, color: 'var(--accent-amber)' }}>Rs. {baseRentAmount.toLocaleString()}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    <span>Electricity ({elecUnits} units @ Rs.{electricity.rate})</span>
                    <span>Rs. {elecCharge.toLocaleString()}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    <span>Water ({waterUnits} units @ Rs.{water.rate})</span>
                    <span>Rs. {waterCharge.toLocaleString()}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    <span>Internet &amp; Garbage</span>
                    <span>Rs. {(directInternet + directGarbage).toLocaleString()}</span>
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--border-color)', paddingTop: '0.6rem', marginTop: '0.2rem' }}>
                    <span style={{ fontWeight: 800, fontSize: '0.925rem' }}>Utility Statement Total:</span>
                    <span style={{ fontSize: '1.35rem', fontWeight: 800, color: 'var(--primary-indigo)' }}>
                      Rs. {totalUtilityCharge.toLocaleString()}
                    </span>
                  </div>
                  <span style={{ fontSize: '0.725rem', color: 'var(--text-muted)', textAlign: 'right' }}>
                    Combined with Base Rent (Rs. {baseRentAmount.toLocaleString()}) = Rs. {calculatedTotalAmount.toLocaleString()}
                  </span>
                </div>

                {/* Meter Dial Photo Attachment Proof (Multiple Photo Upload) */}
                <div className="form-group" style={{ margin: 0 }}>
                  <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontWeight: 700 }}>
                    <Camera size={15} color="var(--primary-indigo)" /> NEA/KUKL Meter Dial Photo Proofs (Upload Multiple)
                  </label>
                  <input
                    type="file"
                    multiple
                    className="form-input"
                    accept="image/*"
                    onChange={handlePhotoSelect}
                    style={{ width: '100%', boxSizing: 'border-box' }}
                  />
                  <span style={{ fontSize: '0.725rem', color: 'var(--text-muted)', display: 'block', marginTop: '0.25rem' }}>
                    Select multiple clear meter dial photos (Electricity &amp; Water meters) to attach to this invoice.
                  </span>

                  {/* Thumbnail Gallery Preview */}
                  {meterPhotos.length > 0 && (
                    <div style={{ display: 'flex', gap: '0.65rem', flexWrap: 'wrap', marginTop: '0.65rem' }}>
                      {meterPhotos.map(photo => (
                        <div key={photo.id} style={{ position: 'relative', width: '70px', height: '70px', borderRadius: '0.5rem', overflow: 'hidden', border: '1px solid var(--border-color)', boxShadow: '0 2px 8px rgba(0,0,0,0.15)' }}>
                          <img src={photo.url} alt="Proof" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                          <button
                            type="button"
                            onClick={() => removePhoto(photo.id)}
                            style={{
                              position: 'absolute',
                              top: '3px',
                              right: '3px',
                              background: 'rgba(239, 68, 68, 0.9)',
                              color: '#ffffff',
                              border: 'none',
                              borderRadius: '50%',
                              width: '18px',
                              height: '18px',
                              fontSize: '10px',
                              fontWeight: 800,
                              cursor: 'pointer',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              boxShadow: '0 2px 4px rgba(0,0,0,0.3)'
                            }}
                            title="Remove Photo"
                          >
                            ✕
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <button 
                  type="submit" 
                  className="btn-primary" 
                  disabled={submitLoading}
                  style={{ width: '100%', marginTop: '0.5rem', padding: '0.85rem', fontWeight: 800, fontSize: '0.95rem' }}
                >
                  {submitLoading ? 'Issuing Bill...' : `Issue Bill for Rs. ${calculatedTotalAmount.toLocaleString()}`}
                </button>
              </form>
            )}
          </div>
        )}

        {/* Right Column: Bill List History */}
        <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', overflowX: 'auto' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 600, margin: 0 }}>Utility Invoice Records</h2>

          {bills.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--text-muted)' }}>
              No utility bills found.
            </div>
          ) : (
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid rgba(255,255,255,0.08)', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                  <th style={{ padding: '0.75rem 0.5rem' }}>Property & Tenant</th>
                  <th style={{ padding: '0.75rem 0.5rem' }}>Billing Month</th>
                  <th style={{ padding: '0.75rem 0.5rem' }}>Amount</th>
                  <th style={{ padding: '0.75rem 0.5rem' }}>Due Date</th>
                  <th style={{ padding: '0.75rem 0.5rem' }}>Status</th>
                  <th style={{ padding: '0.75rem 0.5rem', textAlign: 'center' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {bills.map((bill) => {
                  const billMonth = new Date(bill.billing_month).toLocaleDateString(undefined, { year: 'numeric', month: 'long' });
                  const isPaid = bill.status === 'paid';
                  
                  return (
                    <tr key={bill.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)', fontSize: '0.9rem' }}>
                      <td style={{ padding: '1rem 0.5rem' }}>
                        <div style={{ fontWeight: 600 }}>
                          {bill.agreement_detail?.property?.title || bill.agreement?.property?.title || 'Sanagaun Property'}
                        </div>
                        <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                          Tenant: {bill.agreement_detail?.tenant?.full_name || bill.agreement?.tenant?.full_name || 'Manish Gautam'}
                        </div>
                      </td>
                      <td style={{ padding: '1rem 0.5rem', fontWeight: 500 }}>{billMonth}</td>
                      <td style={{ padding: '1rem 0.5rem', fontWeight: 600 }}>Rs. {parseFloat(bill.total_amount).toLocaleString()}</td>
                      <td style={{ padding: '1rem 0.5rem', color: 'var(--text-muted)' }}>
                        {new Date(bill.due_date).toLocaleDateString()}
                      </td>
                      <td style={{ padding: '1rem 0.5rem' }}>{getStatusBadge(bill.status)}</td>
                      <td style={{ padding: '1rem 0.5rem' }}>
                        <div style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', alignItems: 'center' }}>
                          <button 
                            onClick={() => handleDownloadBillPDF(bill.id)}
                            style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid #6366f1', borderRadius: '0.25rem', padding: '0.35rem 0.6rem', color: '#818cf8', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.25rem' }}
                            title="Download Utility Bill PDF"
                          >
                            <FileText size={14} /> PDF
                          </button>

                          {/* Landlord Toggle Payment Action */}
                          {isLandlord ? (
                            <>
                              <button 
                                onClick={() => handleToggleStatus(bill.id, bill.status)}
                                style={{ background: isPaid ? 'rgba(245,158,11,0.05)' : 'rgba(16,185,129,0.05)', border: `1px solid ${isPaid ? '#f59e0b' : '#10b981'}`, borderRadius: '0.25rem', padding: '0.35rem 0.75rem', color: isPaid ? '#f59e0b' : '#10b981', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 600, transition: 'all 0.2s' }}
                              >
                                {isPaid ? 'Mark Unpaid' : 'Mark Paid'}
                              </button>
                              <button 
                                onClick={() => handleDeleteBill(bill.id)}
                                style={{ background: 'rgba(239,68,68,0.05)', border: '1px solid #ef4444', borderRadius: '0.25rem', padding: '0.35rem 0.5rem', color: '#ef4444', cursor: 'pointer', transition: 'all 0.2s' }}
                              >
                                <Trash size={14} />
                              </button>
                            </>
                          ) : (
                            // Tenant static details/readings display
                            bill.readings?.length > 0 ? (
                              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem', fontSize: '0.75rem', background: 'rgba(255,255,255,0.02)', padding: '0.5rem', borderRadius: '0.25rem', border: '1px solid rgba(255,255,255,0.05)', minWidth: '130px' }}>
                                {bill.readings.map((r) => (
                                  <div key={r.id} style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                                    {getUtilityIcon(r.utility_type)}
                                    <span style={{ textTransform: 'capitalize', fontWeight: 600 }}>{r.utility_type}:</span> 
                                    <span>{parseFloat(r.current_reading) - parseFloat(r.previous_reading)} units</span>
                                  </div>
                                ))}
                              </div>
                            ) : (
                              <span style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>No meter readings</span>
                            )
                          )}

                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>

      </div>

    </div>
  );
}
