# Generated by Django 4.2.30 on 2026-08-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_agreement_landlord_signature_url_and_more'),
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='agreements.agreement'),
        ),
    ]
