# Generated by Django 4.2.30 on 2026-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_historicalagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_doc_status',
            field=models.CharField(choices=[('pending_upload', 'Pending Upload'), ('uploaded_pending_ack', 'Uploaded - Pending Review'), ('acknowledged', 'Acknowledged by Both'), ('rejected', 'Rejected')], default='pending_upload', max_length=30),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_document_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='signed_doc_status',
            field=models.CharField(choices=[('pending_upload', 'Pending Upload'), ('uploaded_pending_ack', 'Uploaded - Pending Review'), ('acknowledged', 'Acknowledged by Both'), ('rejected', 'Rejected')], default='pending_upload', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='signed_document_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
