# Generated by Django 4.2.30 on 2026-08-07 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_agreement_landlord_signature_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='advance_payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='advance_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired - Auto Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='advance_payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='advance_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired - Auto Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending_advance', 'Pending Advance Payment')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending_advance', 'Pending Advance Payment')], default='active', max_length=20),
        ),
    ]
