# Generated by Django 4.2.30 on 2026-08-08 16:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0006_agreement_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='renewal_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='agreement',
            name='renewal_proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_renewals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='renewal_proposed_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='renewal_status',
            field=models.CharField(choices=[('none', 'None'), ('proposed', 'Renewal Proposed'), ('accepted', 'Renewal Accepted'), ('rejected', 'Renewal Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='renewal_increase_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='renewal_proposed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='renewal_proposed_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='renewal_status',
            field=models.CharField(choices=[('none', 'None'), ('proposed', 'Renewal Proposed'), ('accepted', 'Renewal Accepted'), ('rejected', 'Renewal Rejected')], default='none', max_length=20),
        ),
    ]
