# Generated by Django 4.2.30 on 2026-08-06 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedproperty',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='savedproperty',
            old_name='saved_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_bill_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lalpurja_doc_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Audit'), ('verified', 'Verified Listing'), ('flagged', 'Physical Agent Inspection Required')], default='verified', max_length=30),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
