# Generated by Django 4.2.30 on 2026-08-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_savedproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished')], default='unfurnished', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('flat', 'Flat'), ('house', 'Full House')], default='flat', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='photo_url',
            field=models.TextField(),
        ),
    ]
