# Generated by Django 4.2.30 on 2026-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_furnishing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, default='', help_text='Private landmark (revealed only after agreement)', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='tole',
            field=models.CharField(blank=True, default='', help_text='Tole/Locality name', max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='ward_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
