# Generated by Django 4.2.30 on 2026-07-10 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0002_agreement_security_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_type', models.CharField(choices=[('termination', 'Termination Notice'), ('eviction', 'Eviction Notice'), ('rent_arrears', 'Rent Arrears Warning'), ('general', 'General Notice')], max_length=30)),
                ('notice_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('effective_date', models.DateField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='agreements.agreement')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
