# Generated by Django 4.2.30 on 2026-07-09 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('rent_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaPaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_uuid', models.CharField(max_length=100, unique=True)),
                ('esewa_ref_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_logs', to='agreements.agreement')),
                ('rent_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esewa_log', to='rent_payments.rentpayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
