# Generated by Django 4.2.30 on 2026-07-09 10:05

from django.db import migrations, models
import django.db.models.deletion
import rent_payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payments', '0002_esewapaymentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esewapaymentlog',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='esewapaymentlog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='esewapaymentlog',
            name='esewa_ref_id',
        ),
        migrations.RemoveField(
            model_name='esewapaymentlog',
            name='payment_month',
        ),
        migrations.RemoveField(
            model_name='esewapaymentlog',
            name='rent_payment',
        ),
        migrations.AddField(
            model_name='esewapaymentlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esewa_logs', to='rent_payments.rentpayment'),
        ),
        migrations.AddField(
            model_name='esewapaymentlog',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esewapaymentlog',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='esewa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='esewapaymentlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('TAMPERED', 'Tampered')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='esewapaymentlog',
            name='transaction_uuid',
            field=models.CharField(default=rent_payments.models.generate_esewa_transaction_uuid, max_length=100, unique=True),
        ),
    ]
