# Generated by Django 4.2.30 on 2026-07-15 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_historicalagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_payments', '0003_remove_esewapaymentlog_agreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRentPayment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_month', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, editable=False)),
                ('receipt_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_late', models.BooleanField(default=False)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('esewa_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agreements.agreement')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rent payment',
                'verbose_name_plural': 'historical rent payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
