# Generated by Django 4.2.30 on 2026-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payments', '0004_historicalrentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrentpayment',
            name='late_fee_applied_by_landlord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='late_fee_applied_by_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
