# Generated by Django 4.2.30 on 2026-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payments', '0005_historicalrentpayment_late_fee_applied_by_landlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrentpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrentpayment',
            name='receipt_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='receipt_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
