# Generated by Django 5.2.15 on 2026-07-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='lease_duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Proposed lease duration in months. Minimum 1, maximum 60.'),
        ),
    ]
