# Generated by Django 4.2.30 on 2026-07-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_lease_duration_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lease_duration_months',
        ),
    ]
