# Generated by Django 4.2.30 on 2026-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_lease_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
